version: "3.8"

services:
  mssql-spe:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/mssql-spe:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/mssql-spe
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${SQL_BASE_IMAGE}:${SITECORE_VERSION}
        SPE_IMAGE: ${SITECORE_MODULE_REGISTRY}${SPE_ASSET_IMAGE}
  
  mssql-spe-hrz:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/mssql-hrz:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/mssql-hrz
      args:
        BASE_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}/mssql-spe:${VERSION:-latest}
        HRZ_IMAGE: ${SITECORE_MODULE_REGISTRY}${HRZ_ASSET_IMAGE}

  mssql-sxa:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/mssql-sxa:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/mssql-sxa
      args:
        BASE_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}/mssql-spe:${VERSION:-latest}
        SXA_IMAGE: ${SITECORE_MODULE_REGISTRY}${SXA_ASSET_IMAGE}

  mssql-sxa-hrz:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/mssql-sxa-hrz:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/mssql-sxa
      args:
        BASE_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}/mssql-hrz:${VERSION:-latest}
        SXA_IMAGE: ${SITECORE_MODULE_REGISTRY}${SXA_ASSET_IMAGE}

  solr-init:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/solr-init:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/solr
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${SOLR_BASE_IMAGE}:${SITECORE_VERSION}
        SXA_IMAGE: ${SITECORE_MODULE_REGISTRY}${SXA_ASSET_IMAGE}

  solr-init-sxa:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/solr-init-sxa:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/solr-sxa
      args:
        BASE_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}/solr-init:${VERSION:-latest}
        SXA_IMAGE: ${SITECORE_MODULE_REGISTRY}${SXA_ASSET_IMAGE}

  id:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/id:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/id
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${ID_BASE_IMAGE}:${SITECORE_VERSION}

  cd:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/cd:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/cd
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${CD_BASE_IMAGE}:${SITECORE_VERSION}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}${SC_TOOLING_IMAGE}

  cd-sxa:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/cd-sxa:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/cd-sxa
      args:
        BASE_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}/cd:${VERSION:-latest}
        SXA_IMAGE: ${SITECORE_MODULE_REGISTRY}${SXA_ASSET_IMAGE}

  cm-spe:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/cm-spe:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/cm-spe
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${CM_BASE_IMAGE}:${SITECORE_VERSION}
        SPE_IMAGE: ${SITECORE_MODULE_REGISTRY}${SPE_ASSET_IMAGE}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}${SC_TOOLING_IMAGE}
        SMS_IMAGE: ${SITECORE_MODULE_REGISTRY}${SMS_ASSET_IMAGE}

  cm-spe-hrz:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/cm-hrz:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/cm-hrz
      args:
        BASE_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}/cm-spe:${VERSION:-latest}
        HRZ_IMAGE: ${SITECORE_MODULE_REGISTRY}${HRZ_ASSET_IMAGE}

  cm-sxa:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/cm-sxa:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/cm-sxa
      args:
        BASE_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}/cm-spe:${VERSION:-latest}
        SXA_IMAGE: ${SITECORE_MODULE_REGISTRY}${SXA_ASSET_IMAGE}

  cm-sxa-hrz:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/cm-sxa-hrz:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/cm-sxa
      args:
        BASE_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}/cm-hrz:${VERSION:-latest}
        SXA_IMAGE: ${SITECORE_MODULE_REGISTRY}${SXA_ASSET_IMAGE}

  xdbsearchworker:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/xdbsearchworker:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/xdbsearchworker
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${XDB_SEARCHWORKER_BASE_IMAGE}:${SITECORE_VERSION}

  xdbautomationworker:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/xdbautomationworker:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/xdbautomationworker
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${XDB_AUTOMATION_BASE_IMAGE}:${SITECORE_VERSION}

  cortexprocessingworker:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/cortexprocessingworker:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/cortexprocessingworker
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${CORTEX_PROC_BASE_IMAGE}:${SITECORE_VERSION}
    
  xconnect:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/xconnect:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/xconnect
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${XCONNECT_BASE_IMAGE}:${SITECORE_VERSION}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}${SC_TOOLING_IMAGE}