version: "3.8"

services:
  cm-base:
    image:  ${REGISTRY}${COMPOSE_PROJECT_NAME}/cm-xm-spe:${VERSION:-latest}
    build:
      context: ./cm
      args:
        PARENT_IMAGE: ${SITECORE_DOCKER_REGISTRY}${CM_BASE_IMAGE}:${SITECORE_VERSION}
        SPE_IMAGE: ${REGISTRY}${SPE_ASSET_IMAGE}
        TOOLS_IMAGE: ${SITECORE_TOOLS_REGISTRY}${SC_TOOLING_IMAGE} 
        SMS_IMAGE: ${SITECORE_MODULE_REGISTRY}${SMS_ASSET_IMAGE}
  cm-hrz:
    image:  ${REGISTRY}${COMPOSE_PROJECT_NAME}/cm-xm-hrz:${VERSION:-latest}
    build:
      context: ./cm/hrz
      args:
        PARENT_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}/cm-xm-spe:${VERSION:-latest}
        HRZ_IMAGE: ${SITECORE_MODULE_REGISTRY}${HRZ_ASSET_IMAGE}
  cm-hrz-headless:
    image:  ${REGISTRY}${COMPOSE_PROJECT_NAME}/cm-xm-hrz-headless:${VERSION:-latest}
    build:
      context: ./cm/headless
      args:
        PARENT_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}/cm-xm-hrz:${VERSION:-latest}
        HEADLESS_SERVICES_IMAGE: ${SITECORE_MODULE_REGISTRY}${HEADLESS_SERVICES_IMAGE}
  cm-headless:
    image:  ${REGISTRY}${COMPOSE_PROJECT_NAME}/cm-xm-hrz:${VERSION:-latest}
    build:
      context: ./cm/headless
      args:
        PARENT_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}/cm-xm-spe:${VERSION:-latest}
        HEADLESS_SERVICES_IMAGE: ${SITECORE_MODULE_REGISTRY}${HEADLESS_SERVICES_IMAGE}
  nodejs-asset:
    image:  ${REGISTRY}${ASSET_PROJECT_NAME}/nodejs:${NODEJS_VERSION}-${VERSION} 
    build:
      context: ./nodejs/asset
      args:
        PARENT_IMAGE: ${NODEJS_BASE_IMAGE}
        NODEJS_VERSION: ${NODEJS_VERSION}
  nodejs-host:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/nodejs-host:${NODEJS_VERSION}-${VERSION}
    build:
      context: ./nodejs
      args:
        PARENT_IMAGE: ${REGISTRY}${ASSET_PROJECT_NAME}/nodejs:${NODEJS_VERSION}-${VERSION}
  sql-init-spe:
    image:  ${REGISTRY}${COMPOSE_PROJECT_NAME}/sql-init-spe:${VERSION:-latest}
    build:
      context: ./sql/init
      args:
        PARENT_IMAGE: ${SITECORE_DOCKER_REGISTRY}${SQL_INIT_BASE_IMAGE}:${SITECORE_VERSION}
        SPE_IMAGE: ${REGISTRY}${SPE_ASSET_IMAGE}
  sql-init-headless:
    image:  ${REGISTRY}${COMPOSE_PROJECT_NAME}/sql-init-hrz:${VERSION:-latest}
    build:
      context: ./sql/init-headless
      args:
        PARENT_IMAGE: ${REGISTRY}${COMPOSE_PROJECT_NAME}/sql-init-spe:${VERSION:-latest}
        HEADLESS_SERVICES_IMAGE: ${SITECORE_MODULE_REGISTRY}${HEADLESS_SERVICES_IMAGE}
  sql-base:
    image:  ${REGISTRY}${COMPOSE_PROJECT_NAME}/sql-base:${VERSION:-latest}
    build:
      context: .
      args:
        PARENT_IMAGE: ${SITECORE_DOCKER_REGISTRY}nonproduction/mssql-developer:2017-${SITECORE_VERSION}
  solr-init:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/solr-init:${VERSION:-latest}
    build:
      context: .
      args:
        PARENT_IMAGE: ${SITECORE_DOCKER_REGISTRY}${SOLR_INIT_BASE_IMAGE}:${SITECORE_VERSION}
  solr-base:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}/solr-base:${VERSION:-latest}
    build:
      context: .
      args:
        PARENT_IMAGE: ${SITECORE_DOCKER_REGISTRY}nonproduction/solr:8.8.2-${SITECORE_VERSION}