# ltsc2022 corresponds to 10.0.20348.169
# 2004 corresponds to 10.0.19041.1165
# 20H2 corresponds to 10.0.19042.1165

FROM mcr.microsoft.com/windows/nanoserver:20H2 AS build

# Copy assets into the image, keeping the folder structure
COPY \ .\