version: "3.8"

services:
  mssql:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-mssql:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/mssql
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${SQL_BASE_IMAGE}:${SITECORE_VERSION}
        SPE_IMAGE: ${SITECORE_MODULE_REGISTRY}${SPE_ASSET_IMAGE}
        SXA_IMAGE: ${SITECORE_MODULE_REGISTRY}${SXA_ASSET_IMAGE}
  
  solr:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-solr:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/solr
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${SOLR_BASE_IMAGE}:${SITECORE_VERSION}
        SXA_IMAGE: ${SITECORE_MODULE_REGISTRY}${SXA_ASSET_IMAGE}

  id:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-id:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/id
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${ID_BASE_IMAGE}:${SITECORE_VERSION}

  cd:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-cd:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/cd
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${CD_BASE_IMAGE}:${SITECORE_VERSION}
        SXA_IMAGE: ${SITECORE_MODULE_REGISTRY}${SXA_ASSET_IMAGE}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}${SC_TOOLING_IMAGE}        

  cm:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-cm:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/cm
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${CM_BASE_IMAGE}:${SITECORE_VERSION}
        SPE_IMAGE: ${SITECORE_MODULE_REGISTRY}${SPE_ASSET_IMAGE}
        SXA_IMAGE: ${SITECORE_MODULE_REGISTRY}${SXA_ASSET_IMAGE}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}${SC_TOOLING_IMAGE}
        SMS_IMAGE: ${SITECORE_MODULE_REGISTRY}${SMS_ASSET_IMAGE}

  xdbsearchworker:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xdbsearchworker:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/xdbsearchworker
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${XDB_SEARCHWORKER_BASE_IMAGE}:${SITECORE_VERSION}

  xdbautomationworker:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xdbautomationworker:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/xdbautomationworker
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${XDB_AUTOMATION_BASE_IMAGE}:${SITECORE_VERSION}

  cortexprocessingworker:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-cortexprocessingworker:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/cortexprocessingworker
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${CORTEX_PROC_BASE_IMAGE}:${SITECORE_VERSION}
    
  xconnect:
    image: ${REGISTRY}${COMPOSE_PROJECT_NAME}-xconnect:${VERSION:-latest}
    build:
      context: ${SERVICES_PATH}/xconnect
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${XCONNECT_BASE_IMAGE}:${SITECORE_VERSION}
        TOOLING_IMAGE: ${SITECORE_TOOLS_REGISTRY}${SC_TOOLING_IMAGE}